server:
  port: 8085

spring:
  application:
    name: order
  profiles:
    include: seata
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://repo.emon.vip:3306/db_order?useUnicode=true&useSSL=false
    username: root
    password: root123
  jpa:
    show-sql: true