spring:
  datasource:
    url: jdbc:mysql://repo.emon.vip:3306/ds0?useUnicode=true&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root123
  jpa:
    show-sql: true